### ISSUE TITLE
[Bug]: CUDA-capable device(s) is/are busy or unavailable

### ISSUE THREAD

**Issue by Apprisco** [zyddnys/manga-image-translator#1102]
### Issue

Docker compose install with properly working runtime confirmed with other services such as Jellyfin.

CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

<img width="986" height="461" alt="Image" src="https://github.com/user-attachments/assets/41615904-fdc6-499a-9e31-b710e6b57789" />

### Command Line Arguments

```Shell

```

### Console logs

```Shell
clearFinishedItems called
(index):1781 Before clearing: []
(index):1788 After clearing: []
(index):1164 Currently translating: false
(index):1165 Current queue statuses: []
(index):1189 Starting translation with status: processing
(index):1207 Started new translation, reset currentFolder to null
(index):1718 Calculating progress for status: processing
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: processing
(index):1739 Status maps to step: undefined
null:1  GET http://192.168.2.193:5003/null 404 (Not Found)
Image
ye @ petite-vue.iife.js:1
(anonymous) @ petite-vue.iife.js:1
run @ petite-vue.iife.js:1
me @ petite-vue.iife.js:1
Promise.then
he @ petite-vue.iife.js:1
de @ petite-vue.iife.js:1
scheduler @ petite-vue.iife.js:1
Z @ petite-vue.iife.js:1
J @ petite-vue.iife.js:1
(anonymous) @ petite-vue.iife.js:1
clearFinishedItems @ (index):1784
startTranslation @ (index):1155
eval @ VM168:3Understand this error
(index):1718 Calculating progress for status: processing
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: processing
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: processing
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: processing
(index):1739 Status maps to step: undefined
(index):1298 Updating status for queued image: 1767185381999.9175 to: running_pre_translation_hooks
(index):1718 Calculating progress for status: running_pre_translation_hooks
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: running_pre_translation_hooks
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: running_pre_translation_hooks
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: running_pre_translation_hooks
(index):1739 Status maps to step: undefined
(index):1316 CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

processChunk @ (index):1316
uploadWithProgress @ (index):1369
await in uploadWithProgress
processTranslation @ (index):1389
startTranslation @ (index):1191
eval @ VM168:3Understand this error
(index):1718 Calculating progress for status: error
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: error
(index):1739 Status maps to step: undefined
```

**Comment by Apprisco** [comment]
<img width="1081" height="625" alt="Image" src="https://github.com/user-attachments/assets/1b1eb92e-b8e3-492e-a7b0-283e7593dcc2" />

**Comment by Apprisco** [comment]
After updating container toolkit and running with m2m100:

(index):1739 Status maps to step: 3
(index):1757 Progress result: {percentage: 22}
(index):1718 Calculating progress for status: detection
(index):1739 Status maps to step: 3
(index):1757 Progress result: {percentage: 22}
(index):1718 Calculating progress for status: detection
(index):1739 Status maps to step: 3
(index):1757 Progress result: {percentage: 22}
(index):1718 Calculating progress for status: detection
(index):1739 Status maps to step: 3
(index):1757 Progress result: {percentage: 22}
(index):1298 Updating status for queued image: 1767186183782.3074 to: ocr
(index):1718 Calculating progress for status: ocr
(index):1739 Status maps to step: 4
(index):1757 Progress result: {percentage: 33}
(index):1718 Calculating progress for status: ocr
(index):1739 Status maps to step: 4
(index):1757 Progress result: {percentage: 33}
(index):1718 Calculating progress for status: ocr
(index):1739 Status maps to step: 4
(index):1757 Progress result: {percentage: 33}
(index):1718 Calculating progress for status: ocr
(index):1739 Status maps to step: 4
(index):1757 Progress result: {percentage: 33}
(index):1298 Updating status for queued image: 1767186183782.3074 to: textline_merge
(index):1718 Calculating progress for status: textline_merge
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: textline_merge
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: textline_merge
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: textline_merge
(index):1739 Status maps to step: undefined
(index):1298 Updating status for queued image: 1767186183782.3074 to: translating
(index):1718 Calculating progress for status: translating
(index):1739 Status maps to step: 8
(index):1757 Progress result: {percentage: 78}
(index):1718 Calculating progress for status: translating
(index):1739 Status maps to step: 8
(index):1757 Progress result: {percentage: 78}
(index):1718 Calculating progress for status: translating
(index):1739 Status maps to step: 8
(index):1757 Progress result: {percentage: 78}
(index):1718 Calculating progress for status: translating
(index):1739 Status maps to step: 8
(index):1757 Progress result: {percentage: 78}
(index):1316 Library libcublas.so.12 is not found or cannot be loaded
processChunk @ (index):1316
uploadWithProgress @ (index):1369
await in uploadWithProgress
processTranslation @ (index):1389
startTranslation @ (index):1191
eval @ VM169:3Understand this error
(index):1718 Calculating progress for status: error
(index):1739 Status maps to step: undefined
(index):1718 Calculating progress for status: error
(index):1739 Status maps to step: undefined

**Comment by Apprisco** [comment]
Fixed by compiling my own docker image with updated pytorch backend.
